### ISSUE TITLE
increase z index of navbar

### ISSUE THREAD

**Issue by atiqurx** [acmuta/acmuta-site#30]
footer has higher z index

**Comment by KevinRouz** [comment]
Im workin here

**Comment by brunades** [comment]
I would like to contribute towards resolving this. 
After reviewing the current implementation, I believe a more efficient solution would be to decrease the z-index of the footer. Since Tailwind CSS has a maximum z-index value of z-50, which is currently applied to both the navbar and the footer, reducing the footer’s z-index would ensure that the navbar is correctly layered above the footer without needing to exceed Tailwind's defined z values.

May I go ahead and submit a pull request for this adjustment? 
I’d be happy to assist in implementing this solution if you agree.

**Comment by kevinrouz** [comment]
@brunades Absolutely, you can always self-assign and submit a PR.
